services:
    waigeo_js_logger.logsManager:
        class: Waigeo\JSLoggerBundle\Service\LogsManager
        arguments: ["@doctrine.orm.entity_manager"]
    waigeo_js_logger.serializer:
            class: Waigeo\JSLoggerBundle\Utils\JsonSerializer
